---
- name: Ensure Stow installed
  become: yes
  pacman:
    name: stow
    state: present

- name: Build directories list
  find:
    paths: [dotfiles/]
    recurse: no
    file_type: directory
  register: files

- name: Deploy dotfiles!
  with_items: '{{ files.files }}'
  command: 'stow -t ../.. {{ item.path | replace("dotfiles/", "") }}'
  args:
    chdir: ./dotfiles